package View;

import DAO.HistoricoDAO;
import DAO.MusicaDAO;
import Model.Musica;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.PopupMenu;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Lucas Galvano
 */
public class HistoricoFrame extends javax.swing.JFrame {
    private MusicaDAO musicaDAO;
    private HistoricoDAO historicoDAO;
    private int userId; 
    /**
     * Creates new form HistoricoFrame
     */
    public HistoricoFrame(MusicaDAO musicaDAO, HistoricoDAO historicoDAO, int userId) {
        initComponents();
        this.musicaDAO = musicaDAO;
        this.historicoDAO = historicoDAO;
        this.userId = userId;

        setTitle("Histórico do Usuário");
        setSize(600, 600);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new GridLayout(3, 1));

        add(criarPainel("Últimas Músicas Buscadas", "buscadas"));
        add(criarPainel("Últimas Músicas Curtidas", "curtidas"));
        add(criarPainel("Últimas Músicas Descurtidas", "descurtidas"));

        setVisible(true);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JPanel criarPainel(String titulo, String tipo) {
            JPanel painel = new JPanel(new BorderLayout());
            JLabel label = new JLabel(titulo);
            painel.add(label, BorderLayout.NORTH);

            JPanel lista = new JPanel();
            lista.setLayout(new BoxLayout(lista, BoxLayout.Y_AXIS));

            List<Musica> musicas;

            try {
                if (tipo.equals("curtidas")) {
                    musicas = musicaDAO.buscarCurtidas(userId);
                } else if (tipo.equals("descurtidas")) {
                    musicas = musicaDAO.buscarDescurtidas(userId);
                } else {
                    musicas = historicoDAO.procurarBuscas(userId);
                }

                for (Musica m : musicas) {
                    lista.add(new JLabel(m.getNomeMusica() + " - " + m.getArtista() + " (" + m.getGenero() + ")"));
                }
            } catch (Exception e) {
                lista.add(new JLabel("Erro ao carregar histórico: " + e.getMessage()));
            }

            painel.add(new JScrollPane(lista), BorderLayout.CENTER);
            return painel;
        }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}  
