package View;

import DAO.MusicaDAO;
import Model.Musica;
import java.awt.BorderLayout;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Lucas Galvano
 */
public class MusicasCurtidasFrame extends javax.swing.JFrame {
    private MusicaDAO dao;
    private int userId;
    
    /**
     * Creates new form MusicasCurtidasFrame
     */
    public MusicasCurtidasFrame(MusicaDAO dao, int userId) {
        initComponents();
        this.dao = dao;
        this.userId = userId;
        setTitle("Músicas Curtidas");
        setSize(500, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        JLabel titulo = new JLabel("Minhas Músicas Curtidas", JLabel.CENTER);
        titulo.setFont(new Font("Arial", Font.BOLD, 18));
        add(titulo, BorderLayout.NORTH);

        JPanel listaPanel = new JPanel();
        listaPanel.setLayout(new BoxLayout(listaPanel, BoxLayout.Y_AXIS));

        try {
            List<Musica> musicas = dao.buscarCurtidas(userId);
            if (musicas.isEmpty()) {
                listaPanel.add(new JLabel("Nenhuma música curtida."));
            } else {
                for (Musica m : musicas) {
                    listaPanel.add(new JLabel(m.getNomeMusica() + " - " + m.getArtista() + " (" + m.getGenero() + ")"));
                }
            }
        } catch (SQLException e) {
            listaPanel.add(new JLabel("Erro ao carregar músicas curtidas: " + e.getMessage()));
        }

        JScrollPane scrollPane = new JScrollPane(listaPanel);
        add(scrollPane, BorderLayout.CENTER);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
