package View;

import Model.Usuario;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;



/**
 *
 * @author Lucas Galvano
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Usuario usuario) {
        initComponents();
    }

    
    
    //Getters e Setters
    public JButton getBt_buscar_home() {
        return bt_buscar_home;
    }

    public void setBt_buscar_home(JButton bt_buscar_home) {
        this.bt_buscar_home = bt_buscar_home;
    }

    public JButton getBt_curtir_home() {
        return bt_curtir_home;
    }

    public void setBt_curtir_home(JButton bt_curtir_home) {
        this.bt_curtir_home = bt_curtir_home;
    }

    public JLabel getLbl_FEI_home() {
        return lbl_FEI_home;
    }

    public void setLbl_FEI_home(JLabel lbl_FEI_home) {
        this.lbl_FEI_home = lbl_FEI_home;
    }

    public JLabel getLbl_SpotiFEI_home() {
        return lbl_SpotiFEI_home;
    }

    public void setLbl_SpotiFEI_home(JLabel lbl_SpotiFEI_home) {
        this.lbl_SpotiFEI_home = lbl_SpotiFEI_home;
    }

    public JLabel getLbl_descubra_novas_musicas() {
        return lbl_descubra_novas_musicas;
    }

    public void setLbl_descubra_novas_musicas(JLabel lbl_descubra_novas_musicas) {
        this.lbl_descubra_novas_musicas = lbl_descubra_novas_musicas;
    }

    public JLabel getLbl_tocando_agora() {
        return lbl_tocando_agora;
    }

    public void setLbl_tocando_agora(JLabel lbl_tocando_agora) {
        this.lbl_tocando_agora = lbl_tocando_agora;
    }

    public JTextField getTxt_busca_home() {
        return txt_busca_home;
    }

    public void setTxt_busca_home(JTextField txt_busca_home) {
        this.txt_busca_home = txt_busca_home;
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_SpotiFEI_home = new javax.swing.JLabel();
        lbl_FEI_home = new javax.swing.JLabel();
        bt_buscar_home = new javax.swing.JButton();
        txt_busca_home = new javax.swing.JTextField();
        lbl_tocando_agora = new javax.swing.JLabel();
        bt_curtir_home = new javax.swing.JButton();
        lbl_descubra_novas_musicas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_SpotiFEI_home.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_SpotiFEI_home.setForeground(new java.awt.Color(0, 102, 0));
        lbl_SpotiFEI_home.setText("Spoti");

        lbl_FEI_home.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_FEI_home.setForeground(new java.awt.Color(0, 51, 255));
        lbl_FEI_home.setText("FEI");

        bt_buscar_home.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_buscar_home.setText("Buscar");

        txt_busca_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busca_homeActionPerformed(evt);
            }
        });

        lbl_tocando_agora.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        lbl_tocando_agora.setText("Tocando agora:");

        bt_curtir_home.setText("Curtir");

        lbl_descubra_novas_musicas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbl_descubra_novas_musicas.setText("Descubra novas músicas!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tocando_agora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_curtir_home))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_SpotiFEI_home)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_FEI_home, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_busca_home, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 351, Short.MAX_VALUE)
                                .addComponent(lbl_descubra_novas_musicas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_buscar_home)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SpotiFEI_home)
                    .addComponent(lbl_FEI_home)
                    .addComponent(bt_buscar_home)
                    .addComponent(txt_busca_home, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(lbl_descubra_novas_musicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tocando_agora, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_curtir_home, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_busca_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busca_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busca_homeActionPerformed
     
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPrincipal().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar_home;
    private javax.swing.JButton bt_curtir_home;
    private javax.swing.JLabel lbl_FEI_home;
    private javax.swing.JLabel lbl_SpotiFEI_home;
    private javax.swing.JLabel lbl_descubra_novas_musicas;
    private javax.swing.JLabel lbl_tocando_agora;
    private javax.swing.JTextField txt_busca_home;
    // End of variables declaration//GEN-END:variables
}
